### PR TITLE
adaptive ads

### PR DESCRIPTION
**Pull request by theromis**

### CODE REVIEW

**Comment by Stegoo** [comment]
Hi Roman, 

What are you intending to do with the "adFormat " attribute? You don't seem to use it in the file you committed.

**Comment by theromis** [comment]
without it current adaptive ads doesn't work, check current default google insertion code, recommended adaptive banner have a "auto" format, without it doesn't work
<adsense ad-client="ca-pub-123123123" ad-slot="123123123" inline-style="display:block" ad-format="auto"></adsense>

**Comment by Stegoo** [comment]
Ok I did not know about it, I'll publish a new version on npm/bower. Thank you for your commit.

**Comment by theromis** [comment]
at least this option should more visible in readme

**Pull request merged**
