### PR TITLE
Add some responsiveness

### PR DESCRIPTION
**Pull request by mbilbille**
Add new attributes `viewport-min-witdh` and `viewport-max-width` to
control ad display based on viewport width

### CODE REVIEW

**Comment by mbilbille** [comment]
Any update on this?

**Comment by Stegoo** [comment]
Thank you Matthieu! I'm going to bump the version as well

**Comment by Stegoo** [comment]
@mbilbille The lib has been updated to 0.5.0 on npm and bower

**Comment by mbilbille** [comment]
Thanks @Stegoo

**Pull request merged**
